### ISSUE TITLE
Touch behavior stops working after canceling back-swipe gesture

### ISSUE THREAD

**Issue by tamimattafi** [tamimattafi/krop#17]
Cropping grid stops responding after cancelling a back-swipe, zooming with two fingers starts working incorrectly.
This Video demonstrates touch behavior before and after the back-swipe (at 0:14)

https://github.com/user-attachments/assets/2339b34c-777a-4502-a7ef-9f1b1c553d0d

**Comment by tamimattafi** [comment]
Hello @MathiasDL!
Do you have any idea why this could be the case?

**Comment by MathiasDL** [comment]
I had also noticed this issue in my emulator. Not sure, possibly related to lost focus? Maybe some code in a LaunchedEffect that should also be run after the cancelled back gesture? (no access to my computer now)

**Comment by tamimattafi** [comment]
@MathiasDL You are right, it seems like `cropperTouch` stops invoking after the back gesture is cancelled, I have free time today so I will look into it. Thank you for the hint!

**Comment by tamimattafi** [comment]
It seems like logic and loops inside `awaitEachGesture` get stuck, because the `change` inside `event.changes` are consumed by the back swipe gesture, therefore, `change.changedToDown()` and `change.changedToUp()` always return false, and since `pointers` are not decremented, the logic keeps waiting for a "legit" event.

Changing to `changedToDownIgnoreConsumed()` and `change.changedToUpIgnoreConsumed()` fixes the problem.
I don't see any side effects after these changes.

@MathiasDL could you please check if you have time? Since you also noticed this bug, it would be helpful to get feedback before publishing a new version. Changes can be found here #18

**Comment by MathiasDL** [comment]
@tamimattafi The fix works fine for me, thanks!

The swipe gestures don't do anything atm though, they are normally supposed to be an alternative for pressing Back.
This may be intentionally disabled though, it is quite easy to accidentally perform a swipe gesture when cropping, so best leave it as-is imo.

**Comment by tamimattafi** [comment]
@MathiasDL They don't do anything since the dialog disabled back-press dismiss, but some users might turn this on. Maybe there's an option to disable back-swipe for a specific area, where the grid is located, I will look into it.

**Comment by MathiasDL** [comment]
Either way, the corner circles are close to the border of the screen, so it will always be possible to accidentally do a back swipe.
I know I did a lot of accidental swipes so I quickly turned that feature off on my phone

**Comment by tamimattafi** [comment]
@MathiasDL I found a way to [disable swipe gestures](https://github.com/tamimattafi/krop/pull/18/commits/434ba1a2693da4882f58fb39a9effd74736f4731#diff-68be73fb1d5b78e18a3f319e372d73758cbaa89409501e5ef5e006f3fbc3b754) for specific area, but I'm still testing to figure out the correct rect to use, I think this will solve the problem.

**Comment by MathiasDL** [comment]
Works well on my machine.

We may want the Back Gesture (when completed) to actually work though, I noticed the physical back button also does not work, which is probably related. It feels odd that the physical back button does not work, while the back button in the header does work.

**Comment by tamimattafi** [comment]
@MathiasDL The back press behavior is disabled for the crop dialog since `CropperDialogProperties` have `dismissOnBackPress = false` by default. You can turn that on if you want.

**Comment by tamimattafi** [comment]
This will be released in 0.1.5

**Comment by MathiasDL** [comment]
@tamimattafi I did not notice the `dismissOnBackPress` property, it works fine, thanks!

I do think it would make more sense to set that property to true by default, you're not gonna click accidentally on the back button, and the gesture, if accidental, can be cancelled. Also, I may not be the last person who at first thinks this is a bug.

The other 2 properties make sense: use (almost) the full width, and I don't think anybody will click outside the dialog on purpose.

I checked the Git history, and the properties have stayed the same since initial commit, so I don't think it was very "intentional" to set it to false

So, this would make more sense to me:

```kotlin
val CropperDialogProperties = (DialogProperties(
    usePlatformDefaultWidth = false,
    dismissOnBackPress = true, // changed
    dismissOnClickOutside = false
))
```

Note that this would be kindof a breaking change, so would warrant at least a minor version bump.

What do you think?

**Comment by tamimattafi** [comment]
@MathiasDL I agree, let's change the default behavior in 0.2.0
