### ISSUE TITLE
implementation

### ISSUE THREAD

**Issue by mahramane** [tamimattafi/krop#3]
Hi
Thank you for working on multiplatform version.
How can we implementation it?

**Comment by tamimattafi** [comment]
Hello @mahramane!
I published the library to `mavenCentral` in this [Pull Request](https://github.com/tamimattafi/krop/pull/4).
Please read the [README](https://github.com/tamimattafi/krop/blob/main/README.md) file on how to implement the library in your project.

**Comment by tamimattafi** [comment]
Hello @mahramane!
Did the instructions above help you with implementation?

**Comment by tamimattafi** [comment]
Closing this issue due to no feedback.
