### ISSUE TITLE
Support EXIF orientation (e.g. rotation)

### ISSUE THREAD

**Issue by MathiasDL** [tamimattafi/krop#9]
The library currently does not read EXIF data. EXIF orientation is used by Android to a.o rotate images. This causes some images to appear in a wrong orientation when cropping.

Relevant StackOverflow: https://stackoverflow.com/a/57389676/2260402

**Comment by tamimattafi** [comment]
Hello @MathiasDL!
Thank you for the issue, I had issues with rotation before, so I will try to fix this as I find spare time. Probably not earlier than the weekends.

**Comment by MathiasDL** [comment]
I'm gonna give this issue a try

**Comment by tamimattafi** [comment]
@MathiasDL I already fixed it locally, please wait a bit and I will make a PR

**Comment by tamimattafi** [comment]
@MathiasDL Pushed changes to #20 
I will test this a bit before merging, would you like to review the code?

**Comment by tamimattafi** [comment]
This will be released in 0.1.5
